### ISSUE TITLE
Spotify API Issue Umlaut

### ISSUE THREAD

**Issue by MADITT** [skaupper/VirtualJukebox#69]
If I issue an  queryTracks request with pattern = Am%C3%96 ("AlmÖ) i get a statuscode 500 with json couldn't be parsed as error message. 
I added a Log output to the spotify response in the SpotifyAPI.cpp:68 and it turned out that the response was empty which caused the error.

**Comment by janeson332** [comment]
Should be fixed with #65 
Problem was german umlauts are represented with 2Bytes, not with 1.
But there is also a problem with the spotify web API, because the response code of the request is 400 (Bad Request). And when this code appears they always send an body with a error message (and also the error code).

**Comment by janeson332** [comment]
fixed with #65
